"""empty message

Revision ID: 3485b310e947
Revises: cf03b69d59b7
Create Date: 2021-09-15 17:47:13.620045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3485b310e947'
down_revision = 'cf03b69d59b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_user_id_fkey', 'cities', type_='foreignkey')
    op.drop_column('cities', 'user_id')
    op.drop_constraint('countries_user_id_fkey', 'countries', type_='foreignkey')
    op.drop_column('countries', 'user_id')
    op.add_column('user', sa.Column('cities_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('countries_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'cities', ['cities_id'], ['id'])
    op.create_foreign_key(None, 'user', 'countries', ['countries_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'countries_id')
    op.drop_column('user', 'cities_id')
    op.add_column('countries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('countries_user_id_fkey', 'countries', 'user', ['user_id'], ['id'])
    op.add_column('cities', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cities_user_id_fkey', 'cities', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
